const USER_ROLES = {
  USER: "USER",
  ORGANIZER: "ORGANIZER",
  ADMIN: "NEW_ADMIN"
};

const VALID_ROLES = Object.values(USER_ROLES);

const TOURNAMENT_STATES = {
  ANNOUNCED: "ANNOUNCED",
  OPEN_REGISTRATION: "OPEN_REGISTRATION",
  CLOSED_REGISTRATION: "CLOSED_REGISTRATION",
  IN_PROGRESS: "IN_PROGRESS",
  FINISHED: "FINISHED"
};

//TOURNAMENT TYPES on helper.js

const VALID_T_STATES = Object.values(TOURNAMENT_STATES);
//TOURNAMENT TYPES on helper.js

const T_REGISTRATION_STATUS = {
  PENDING: "PENDING",   //Default
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED"
};

const VALID_TR_STATUS = Object.values(T_REGISTRATION_STATUS);

const GAMES_STATUS = {
  UNASSIGNED: "TODEFINEPLAYERS",
  PENDING: "PENDING",
  COMPLETED: "COMPLETED"
};

const GAMES_RESULTS = {
  TIE : 0,
  PLAYER1: 1,
  PLAYER2: 2,
};  

const VALID_GAMES_STATUS = Object.values(GAMES_STATUS);
const VALID_GAMES_RESULTS = Object.values(GAMES_RESULTS);

module.exports = { 
  USER_ROLES, VALID_ROLES,
  TOURNAMENT_STATES, VALID_T_STATES,
  T_REGISTRATION_STATUS, VALID_TR_STATUS,
  GAMES_STATUS, GAMES_RESULTS, VALID_GAMES_STATUS, VALID_GAMES_RESULTS,
};