name: 'test' 
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Install deps
        uses: devcontainers/ci@v0.3
        with:
          runCmd: npm install --include=dev

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: npm test
